### ISSUE TITLE
Simplify check

### ISSUE THREAD

**Issue by gisostallenberg** [dfridrich/PhpMimeType#3]
You could extract the extension easier by using:

``` php
$extension = pathinfo($filename, PATHINFO_EXTENSION);
if($extension === ''){
   return 'application/octet-stream';
}
```

I can provide a pull request if you want me to

**Comment by dfridrich** [comment]
Hi, great, please make PR, I'll merge. Thanks! :)

**Comment by dfridrich** [comment]
Hi, I made some changes to package, please submit your PR, I'll merge it to v2.0.0.

**Comment by gisostallenberg** [comment]
You replaced the pathinfo with SplFileInfo, which makes the check different
I will provide a PR for an empty extension

**Comment by dfridrich** [comment]
Hi, I just pushed many changes for version 2, see changelog.
